version: "3"

services:
    app:
        build:
            args:
                user: docker-user #change this and reconfigure this with appropriate permission
                uid: 1000 #change this and reconfigure this with appropriate permission
            context: ./
            dockerfile: Dockerfile
        image: app
        container_name: app-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app

    db:
        image: mysql:8.0
        container_name: app-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            #            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d #work on this later
        networks:
            - app

    nginx:
        image: nginx:alpine
        container_name: app-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - app

networks:
    app:
        driver: bridge
